INSERT INTO dba.Niveau_cours (idNiveau, Niveau)
 VALUES
 ('N01', 'Primaire')
 ('N02', 'Secondaire')
 ('N03', 'Supérieur')

INSERT INTO dba.Professeurs (idProfesseurs, Nom, Prenom, Image, idNiveau)
 VALUES
 ('P01', 'Dumbledore', 'Albus', , 'N03')
 ('P02', 'Farnsworth', 'Hubert', , 'N01')
 ('P03', 'Hoover', 'Elizabeth', , 'N01')
 ('P04', 'Jones', 'Indiana', , 'N03')
 ('P05', 'Langdon', 'Robert', , 'N03')
 ('P06', 'McGonagall', 'Minerva', , 'N03')
 ('P07', 'Suresh', 'Mohinder', , 'N03')
 ('P08', 'Mosby', 'Ted', , 'N03')
 ('P09', 'Tournesol', 'Tryphon', , 'N02')
 ('P10', 'Xavier', 'Charles', , 'N03')

INSERT INTO dba.Matieres (idMatieres, Matieres)
 VALUES
 ('M01', 'Mathématiques')
 ('M02', 'Français')
 ('M03', 'Anglais')
 ('M04', 'Néerlandais')
 ('M05', 'Informatique')
 ('M06', 'Architecture')
 ('M07', 'Biologie')
 ('M08', 'Chimie')
 ('M09', 'Physique')
 ('M10', 'Economie')
 ('M11', 'Histoire')
 ('M12', 'Sciences')
 ('M13', 'Géographie')
 ('M14', 'Statistiques')
 ('M15', 'Droit')
 ('M16', 'Marketing')
 ('M17', 'Communication')
 ('M18', 'Psychologie')

INSERT INTO dba.Matieres_professeurs (idProfesseurs, idMatieres)
 VALUES
 ('P01', 'M18')
 ('P02', 'M01')
 ('P03', 'M02')
 ('P04', 'M13')
 ('P05', 'M11')
 ('P06', 'M15')
 ('P07', 'M08')
 ('P08', 'M06')
 ('P09', 'M12')
 ('P10', 'M07')

INSERT INTO dba.Tranche_prix (idPrix, Prix)
('PR01', '5€ -> 7€')
('PR02', '7€ -> 9€')
('PR03', '9€ -> 11€')
('PR04', '11€ -> 14€')
